In [1]:
from tkinter import *
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB

In [2]:
l1 = ['Database Fundamentals', 'Computer Architecture', 'Distributed Computing Systems', 'Cyber Security', 'Networking', 'Software Development', 'Programming Skills', 'Project Management', 'Computer Forensics Fundamentals', 'Technical Communication', 'AI ML', 'Software Engineering', 'Business Analysis', 'Communication skills', 'Data Science', 'Troubleshooting skills', 'Graphics Designing']


In [3]:
Role = ['AI ML Specialist',
          'API Integration Specialist',
          'Application Support Engineer',
          'Business Analyst',
          'Customer Service Executive',
          'Cyber Security Specialist',
          'Data Scientist',
          'Database Administrator',
          'Graphics Designer',
          'Hardware Engineer',
          'Helpdesk Engineer',
          'Information Security Specialist',
          'Networking Engineer',
          'Project Manager',
          'Software Developer',
          'Software Tester',
          'Technical Writer']


In [4]:
l2=[]
for x in range(0,len(l1)):
    l2.append(0)

In [5]:
df=pd.read_csv("C:/Users/vaish/OneDrive/Desktop/moddata.csv")  

df.replace({'Role': {
    'AI ML Specialist': 0,
    'API Integration Specialist': 1,
    'Application Support Engineer': 2,
    'Business Analyst': 3,
    'Customer Service Executive': 4,
    'Cyber Security Specialist': 5,
    'Data Scientist': 6,
    'Database Administrator': 7,
    'Graphics Designer': 8,
    'Hardware Engineer': 9,
    'Helpdesk Engineer': 10,
    'Information Security Specialist': 11,
    'Networking Engineer': 12,
    'Project Manager': 13,
    'Software Developer': 14,
    'Software Tester': 15,
    'Technical Writer': 16
}}, inplace=True)


In [6]:
X= df[l1]

y = df[["Role"]]
np.ravel(y)

array([7, 7, 7, ..., 8, 8, 8], dtype=object)

In [7]:
import pandas as pd
from sklearn.model_selection import train_test_split

# Read the dataset
df = pd.read_csv("C:/Users/vaish/OneDrive/Desktop/moddata.csv")

# Replace Role with numerical values
df.replace({'Role': {
    'AI ML Specialist': 0,
    'API Specialist': 1,
    'Application Support Engineer': 2,
    'Business Analyst': 3,
    'Customer Service Executive': 4,
    'Cyber Security Specialist': 5,
    'Data Scientist': 6,
    'Database Administrator': 7,
    'Graphics Designer': 8,
    'Hardware Engineer': 9,
    'Helpdesk Engineer': 10,
    'Information Security Specialist': 11,
    'Networking Engineer': 12,
    'Project Manager': 13,
    'Software Developer': 14,
    'Software tester': 15,
    'Technical Writer': 16
}}, inplace=True)

# Define features and target variable
X = df.drop(columns=['Role'])  # Features
y = df['Role']  # Target variable

# Split dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Check the shapes of the resulting datasets
print("Train dataset shape:", X_train.shape, y_train.shape)
print("Test dataset shape:", X_test.shape, y_test.shape)


Train dataset shape: (7343, 17) (7343,)
Test dataset shape: (1836, 17) (1836,)


In [8]:
# Write test dataset to a new CSV file
test_data = pd.concat([X_test, y_test], axis=1)
test_data.to_csv("test_data.csv", index=False)


In [9]:
tr=pd.read_csv("C:/Users/vaish/OneDrive/Desktop/train mode.csv") 

In [10]:
tr.replace({'Role': {
    'AI ML Specialist': 0,
    'API Specialist': 1,
    'Application Support Engineer': 2,
    'Business Analyst': 3,
    'Customer Service Executive': 4,
    'Cyber Security Specialist': 5,
    'Data Scientist': 6,
    'Database Administrator': 7,
    'Graphics Designer': 8,
    'Hardware Engineer': 9,
    'Helpdesk Engineer': 10,
    'Information Security Specialist': 11,
    'Networking Engineer': 12,
    'Project Manager': 13,
    'Software Developer': 14,
    'Software tester': 15,
    'Technical Writer': 16
}}, inplace=True)

X_test= tr[l1]
y_test = tr[["Role"]]
np.ravel(y_test)

array([ 7,  9,  2,  5, 14,  1, 13, 11, 16,  0, 15,  3,  4,  6, 10,  8],
      dtype=int64)

In [11]:
import numpy as np

# Replace the role names with numeric values if needed, mapping unexpected values to -1
tr.replace({'Role': {
    'AI ML Specialist': 0,
    'API Integration Specialist': 1,
    'Application Support Engineer': 2,
    'Business Analyst': 3,
    'Customer Service Executive': 4,
    'Cyber Security Specialist': 5,
    'Data Scientist': 6,
    'Database Administrator': 7,
    'Graphics Designer': 8,
    'Hardware Engineer': 9,
    'Helpdesk Engineer': 10,
    'Information Security Specialist': 11,
    'Networking Engineer': 12,
    'Project Manager': 13,
    'Software Developer': 14,
    'Software Tester': 15,
    'Technical Writer': 16,
    'API Specialist': -1,  # Unexpected value mapped to -1
    'Software tester': -1  # Unexpected value mapped to -1
}}, inplace=True)

# Extract features X_test and target variable y_test
X_test = tr[l1]
y_test = tr["Role"].values  # Extract as numpy array
y_test_flattened = np.ravel(y_test)

print(y_test_flattened)


[ 7  9  2  5 14  1 13 11 16  0 15  3  4  6 10  8]


In [12]:
def DecisionTree():

    from sklearn import tree

    clf3 = tree.DecisionTreeClassifier()   
    clf3 = clf3.fit(X,y)


    inter = [Interest1.get(),Interest2.get(),Interest3.get(),Interest4.get(),Interest5.get()]

    for k in range(0,len(l1)):
        # print (k,)
        for z in inter:
            if(z==l1[k]):
                l2[k]=1

    inputtest = [l2]
    predict = clf3.predict(inputtest)
    predicted=predict[0]

    h='no'
    for a in range(0,len(Role)):
        if(predicted == a):
            h='yes'
            break


    if (h=='yes'):
        t1.delete("1.0", END)
        t1.insert(END, Role[a])
    else:
        t1.delete("1.0", END)
        t1.insert(END, "Not Found")


In [13]:
def randomforest():
    from sklearn.ensemble import RandomForestClassifier
    clf4 = RandomForestClassifier()
    clf4 = clf4.fit(X,np.ravel(y))

    inter = [Interest1.get(),Interest2.get(),Interest3.get(),Interest4.get(),Interest5.get()]

    for k in range(0,len(l1)):
        for z in inter:
            if(z==l1[k]):
                l2[k]=1

    inputtest = [l2]
    predict = clf4.predict(inputtest)
    predicted=predict[0]

    h='no'
    for a in range(0,len(Role)):
        if(predicted == a):
            h='yes'
            break

    if (h=='yes'):
        t2.delete("1.0", END)
        t2.insert(END, Role[a])
    else:
        t2.delete("1.0", END)
        t2.insert(END, "Not Found")


In [14]:
def NaiveBayes():
    from sklearn.naive_bayes import GaussianNB
    gnb = GaussianNB()
    gnb=gnb.fit(X,np.ravel(y))


    inter = [Interest1.get(),Interest2.get(),Interest3.get(),Interest4.get(),Interest5.get()]
    for k in range(0,len(l1)):
        for z in inter:
            if(z==l1[k]):
                l2[k]=1

    inputtest = [l2]
    predict = gnb.predict(inputtest)
    predicted=predict[0]

    h='no'
    for a in range(0,len(Role)):
        if(predicted == a):
            h='yes'
            break

    if (h=='yes'):
        t3.delete("1.0", END)
        t3.insert(END, Role[a])
    else:
        t3.delete("1.0", END)
        t3.insert(END, "Not Found")

In [15]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB

# Splitting the dataset into features (X) and target (y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Training the Decision Tree classifier
clf_dt = tree.DecisionTreeClassifier()
clf_dt.fit(X_train, y_train)

# Makeing predictions on the test set
y_pred_dt = clf_dt.predict(X_test)

# Calculating accuracy of Decision Tree
accuracy_dt = accuracy_score(y_test, y_pred_dt)
print("Decision Tree Accuracy:", accuracy_dt)

# Training the Random Forest classifier
clf_rf = RandomForestClassifier()
clf_rf.fit(X_train, y_train)

# Making predictions on the test set
y_pred_rf = clf_rf.predict(X_test)

# Calculating accuracy of Random Forest
accuracy_rf = accuracy_score(y_test, y_pred_rf)
print("Random Forest Accuracy:", accuracy_rf)

# Training the Naive Bayes classifier
clf_nb = GaussianNB()
clf_nb.fit(X_train, y_train)

# Making predictions on the test set
y_pred_nb = clf_nb.predict(X_test)

# Calculating accuracy of Naive Bayes
accuracy_nb = accuracy_score(y_test, y_pred_nb)
print("Naive Bayes Accuracy:", accuracy_nb)


Decision Tree Accuracy: 0.9553376906318083


Random Forest Accuracy: 0.9553376906318083
Naive Bayes Accuracy: 0.9547930283224401


In [16]:
pip install easygui

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [17]:
import easygui
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB

# Functions for prediction

def DecisionTree(interests):
    clf = tree.DecisionTreeClassifier()
    clf = clf.fit(X, y)

    inputtest = [1 if interest in interests else 0 for interest in l1]
    predict = clf.predict([inputtest])[0]
    return Role[predict]

def RandomForest(interests):
    clf = RandomForestClassifier()
    clf = clf.fit(X, np.ravel(y))

    inputtest = [1 if interest in interests else 0 for interest in l1]
    predict = clf.predict([inputtest])[0]
    return Role[predict]

def NaiveBayes(interests):
    gnb = GaussianNB()
    gnb = gnb.fit(X, np.ravel(y))

    inputtest = [1 if interest in interests else 0 for interest in l1]
    predict = gnb.predict([inputtest])[0]
    return Role[predict]

# Main function

def main():
    #list of interests
    interests = easygui.multchoicebox("Select your interests:", "Interests", l1)

    if interests:
        # Making predictions
        decision_tree_prediction = DecisionTree(interests)
        random_forest_prediction = RandomForest(interests)
        naive_bayes_prediction = NaiveBayes(interests)

        # Showing predictions
        easygui.msgbox(f"Decision Tree Prediction: {decision_tree_prediction}\n"
                       f"Random Forest Prediction: {random_forest_prediction}\n"
                       f"Naive Bayes Prediction: {naive_bayes_prediction}",
                       "Predictions")
    else:
        easygui.msgbox("Please select at least one interest.", "Error")

#main function
if __name__ == "__main__":
    main()


c:\Users\vaish\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
c:\Users\vaish\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
c:\Users\vaish\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(
